name: Deploy Dockerized App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/interactive-form:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/interactive-form:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Start EC2 instance
        env:
          INSTANCE_NAME: ${{ secrets.EC2_INSTANCE_NAME }}
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$INSTANCE_NAME" --query "Reservations[0].Instances[0].InstanceId" --output text)
          aws ec2 start-instances --instance-ids $INSTANCE_ID
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Wait for EC2 to be accessible
        run: |
          sleep 60
          for i in {1..10}; do
            ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ${{ secrets.EC2_USER }}@$INSTANCE_IP 'echo SSH connection established' && break
            sleep 10
          done

      - name: Deploy to EC2
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/interactive-form:latest
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ${{ secrets.EC2_USER }}@$INSTANCE_IP << EOF
            docker pull $DOCKER_IMAGE
            docker stop web || true
            docker rm web || true
            docker run -d --name web -p 3000:3000 $DOCKER_IMAGE
          EOF